### ISSUE TITLE
Formalized comment tasks

### ISSUE THREAD

**Issue by Brochato** [TypeCobolTeam/TypeCobol#1023]
This is a task manager for  the creation of the Formalized comments syntaxe.
See #998.

Tasks
- [x] **Tokens and scanner :** (#1012 ) We need to create Formalized comments specific tokens which is not applicable outside a Formalized comments. In the same way Cobol Tokens must not be visible in a Formalized comments

- [x] **Code Elements :** (#1022) With the tokens created, we need to establish a Code Element building grammar an apply it in order to create our Code Elements

- [x] **Nodes :** (#1013) We need tu use the Code Elements created to extend the appropriate Nodes.

- [x] **Generation :** (#1136) We need to generate the documentation using these information in addition of the Cobol code extracted data.
