### ISSUE TITLE
Give up Razor and Skeleton for Code Generation

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1028]
According to issue #991 it came that  with current translation templates based on Razor scripts, we fail to generate an exact code for situations like thoses described in #991.
So we need to write C# code for handling function declaration code generation.

Sub-tasks:
- [x] #1048 Review and Update Skeleton xml file xsd schema (A02.T02) 
- [x] #1049 Specify the attributed grammar of a Skeleton.xml file(A04.T01) 
- [x] #1150 Write the SAX Parser of a Skeleton.xml file (A04.T02)
- [x] #1151 Implement the instantiation of Razor Parser for a target script language. (A05.T01)
- [x] #1152 Implement the transpilation of a C# Razor Script to C# instructions (A06.T01)
- [x] #1153 Generate C# execution code for Skeleton actions on Nodes. (A06.T01)
- [x] #1154 Generate the Skeleton.cs file from the Skeleton.xml file. (A08.T01)
- [x] #1155 Adapt Codegen to work with the generated Skeleton.cs fil. (A09.T01).
- [x] #1178 PullRequest Newcodegen
- [x] #1218 Add a MSBuild task to auto generate C# Skeleton file. 

...To complete

**Comment by mayanje** [comment]
For the requirements (Needs), yes the new Codegen must effectvely support various generation scheme, so it must be flexible and customizable, and Node directed.
For the notion of basic template support, I think we must start thinking about tree pattern matching towards a rewriting system.

**Comment by mayanje** [comment]
Another Idea for code generation customization, is to be driven by the parser, that is to say to use the same Cup parser used to create the AST, but now to perform CodeGen action on specific nodes, while still being Node directed.

**Comment by mayanje** [comment]
Ok this is another Idea: It seems to be in contradiction, but why give up razor and skeleton? Why not create our skeleton C# code generator tool. The tool will take our current Skeleton.xml file and generates a Skeleton.cs file to be compiled. The Skeleton.cs file will not call razor or use razor , but it will contains substituted code for all razor pattern as C# code for condition's type node.
I like this idea.
