### ISSUE TITLE
Implement real Symbol Tables

### ISSUE THREAD

**Issue by mayanje** [TypeCobolTeam/TypeCobol#1278]
TypeCobol uses Symbol Tables that does not contains symbol but rather references to Syntactical nodes in the abstract Syntax Tree, that declare constructions.
So TypeCobol Symbol Table are dictonaries of name to Syntax nodes representing syntactical construction like: Variable declaration, Function declaration, Type declrataion etc...
So where a symbol is needed, TypeCobol use what is called a SymbolReference instance, which is simply a name decorated with symbol category informations not related to a Symbol table. Thus for instance the unicity of a SymbolReference to a same variable is not handled.

This task could reuse what will be done for: Register, represent and implement semantic domain objects (A01.T01) #1262
- [ ] #1284 What about using .resx resource file. 
- [ ] #1262 Register, represent and implement semantic domain objects (A01.T01)
- [ ] #1264 Elaborate the semantic domain. (A02.T02)
- [ ] #1285 Unify DataFlow diagnostics and TypeCobol diagnostics.

**Comment by rooksdo** [comment]
New Symbol Table dropped.
