### ISSUE TITLE
Indexes cannot be qualified so indexes in types could lead to ambiguous indexes

### ISSUE THREAD

**Issue by smedilol** [TypeCobolTeam/TypeCobol#663]
```cobol
01 MyType TYPEDEF STRICT.
     05 MyArray occurs 5 indexed by MyIndex.


01 var1 type MyType.
01 var2 type MyType.

*You cannot write:
set MyIndex of var1 to 1   <- forbidden by IBM Compiler
```
So there is no way in Cobol 85 to qualify an index.

The workaround is to allow qualifying Index with operator `::` (still forbid it with operators `OF` or `IN`).

Then when the code is translated to Cobol 85, we have to add a Hash based on the qualified name of the index at the beginning of index name.
As a result the max length of an index name must be shorten.

Summary
- [x] Variable name inside `TYPEDEF` cannot conflict variable outside this `TYPEDEF` (#697)
- [x] Create an error if an index is qualified with operators `OF` or `IN` (#698)
- [x] Allow Index qualification with operator `::` (#699)
- [x] Qualified index that are not directly in the editable source file (eg. in a COPY) must have an unique name without the prefix qualification (#699)
- [x] Limit Index name that have been qualified and which name are not unique OR inside a `TYPEDEF` to 22 chars (#699)
- [x] Allow qualified name after `DEPENDING ON`with operators `OF`, `IN` or `::` (#672)
- [x] During codegen `DEPENDING ON` inside a `TYPE` must be fully qualified (#700)
- [x] During codegen create an unique name for the index that have been qualified and are in the editable source file : add Hash of 8 chars (starting with a letter) based on the qualified name of the index (#701)
- [x] Replace all qualified references of indexes that have been qualified and which name are not unique OR inside `TYPEDEF` with the unique name of the index (Hash + the rest of its name). (#701)

TODO add #708 and #709

**Comment by smedilol** [comment]
Unit test for index and current working status in comment:
```cobol

       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       DATA DIVISION.
       working-storage section.
      
      
       01 Var1.
      *Bug codegen : MyIdx should be prefixed with a hash
           05 Tab1 occurs 99 indexed by MyIdx.
      
      *Ok, index name neverd used and over 22 chars is accepted
           05 Tab2 occurs 99 indexed by MyIdx2dfsdfzezerzerzerzerzerz.
      
      *Bug, index name is used and over 22 chars but no error
      *Bug codegen : MyIdx should be prefixed with a hash
           05 Tab3 occurs 99 indexed by MyIdx3azeazeazeazeazeazeazeaz.
      
      *Bug : Allow index name over 22 chars if it's not referenced
      *    05 Dup1 occurs 99 indexed by MyIdxsdfsdfzezerzerzerzerzerz.
      *    05 Dup2 occurs 99 indexed by MyIdxsdfsdfzezerzerzerzerzerz.
      
      
       01 MyType TYPEDEF STRICT.
      *Could be better: codegen index name is set to upper-case
      *                 it could maintain case.
           05 MyTab occurs 99 indexed by MyIdXXXXXXXXXXXXXXX.
      
       01 Var1 type MyType.
      
       procedure division.
      *Bug codegen : MyIdx should be prefixed with a hash
           set MyIdx             to 1
      *Bug codegen : MyIdx should be prefixed with a hash
           set MyIdx             up by 1
           set Var1::MyIdx       to 1
           set Var1::MyIdx       up by 1
           set Var1::Tab1::MyIdx to 1
           set Var1::Tab1::MyIdx up by 1
      
      
      
      *Bug codegen : This index should be prefixed with a hash
           set MyIdx3azeazeazeazeazeazeazeaz             to 1
           set Tab3::MyIdx3azeazeazeazeazeazeazeaz       to 1
           set Var1::Tab3::MyIdx3azeazeazeazeazeazeazeaz to 1
      
      *BUG codegen:  This index should be prefixed wih hash
           set MyIdXXXXXXXXXXXXXXX              to 1
           set var1::MyIdXXXXXXXXXXXXXXX        to 1
           set MyTab::MyIdXXXXXXXXXXXXXXX       to 1
           set var1::MyTab::MyIdXXXXXXXXXXXXXXX to 1
      
           set var1::MyIdXXXXXXXXXXXXXXX        up by 1
           set MyTab::MyIdXXXXXXXXXXXXXXX       up by 1
           set var1::MyTab::MyIdXXXXXXXXXXXXXXX up by 1
           goback
           .
       declare procedure IsPersonValid private
                 input  param1      pic X.
       data division.
       working-storage section.
       procedure division.
      
           goback
           .
       end-declare.
       END PROGRAM DVZF0OSM.
```

Unit test for depending on and current status in comment:
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DVZF0OSM.
       DATA DIVISION.
       working-storage section.
      
      
       01 Var1.
           05 Counter pic 9.
      *    05 Tab1 occurs 99 depending on Counter indexed by MyIdx.
           05 Tab2 occurs 99 depending on Var1::Counter
                             indexed by MyIdx2.
           05 Tab3 occurs 99 depending on Counter of Var1
                             indexed by MyIdx3.
           05 Tab4 occurs 99 depending on Counter IN Var1
                             indexed by MyIdx4.
      
      
       01 MyType TYPEDEF STRICT.
         02 Var2.
           05 Counter pic 9.
           05 Tab1 occurs 99 depending on Counter indexed by MyIdx.
      *Bug it warns of MyIdx2 already defined but it won't be the case
      *in code gen
           05 Tab2 occurs 99 depending on Var2::Counter
                             indexed by MyIdx2.
           05 Tab3 occurs 99 depending on Counter of Var2
                             indexed by MyIdx3.
           05 Tab4 occurs 99 depending on Counter IN Var2
                             indexed by MyIdx4.
      
       01 Var2 type MyType.
      
       procedure division.
           goback
           .
       END PROGRAM DVZF0OSM.
```
